server:
  swagger:
    display: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://test.eureka1.msh.com:18000/eureka/
spring:
  datasource: #以下数据库部分自行修改
    url: jdbc:mysql://test.mysql1.msh.com:3306/fastdevelop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 5523003
  redis: #以下redis部分自行修改
    host: test.redis1.msh.com
    port: 6379
    #       password: dh35hebsd87ed9df9d0kemd9
    database: 0

com:
  msh:
    frame:
      common:
        logMethodStart: "*"
logging:
  level:
    root: info
    com:
      msh: debug
      shihu: 
        artascope: 
          sys: 
            sys: debug
